export interface News {
    id: number,
    title: string,
    content: string,
    category: string,
    publish_date: string,
    region: string,
    resources: string,
    author_name: string,
    viewes: number,
    likes: number,
    rep: number,
    liked: boolean,
    plus_rep: boolean,
    viewed: boolean,
    favorited: boolean,
    approved: boolean,
    by_current: boolean,
}