"""create_favorite_table

Revision ID: 1af365fab8b7
Revises: 2e359866195e
Create Date: 2022-05-11 03:02:33.118116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1af365fab8b7'
down_revision = '2e359866195e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_news', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_news'], ['news.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_user', 'id_news')
    )
    op.drop_column('user', 'birthday')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('birthday', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_table('favorite')
    # ### end Alembic commands ###
