"""change comment primary key

Revision ID: 2e359866195e
Revises: 44c44d5ed44f
Create Date: 2022-04-26 11:07:34.869298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e359866195e'
down_revision = '44c44d5ed44f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('id', sa.Integer(), nullable=False))
    # op.drop_constraint('PRIMARY', 'id_user', type_='primary')
    op.drop_constraint('comment_pkey', 'comment', type_='primary')
    op.create_primary_key('comment_pkey', 'comment', ['id'])
    op.alter_column('comment', 'id_user',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comment', 'id_news',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.execute('''CREATE SEQUENCE IF NOT EXISTS public.comment_id_seq
                    INCREMENT 1
                    START 1
                    MINVALUE 1
                    MAXVALUE 2147483647
                    CACHE 1
                    OWNED BY "comment".id;
                ALTER TABLE IF EXISTS public.comment
                    ALTER COLUMN id SET DEFAULT nextval('comment_id_seq'::regclass);''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'id_news',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('comment', 'id_user',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('comment_pkey', 'comment', type_='primary')
    op.create_primary_key('comment_pkey', 'comment', ['id_news', 'id_user'])
    op.drop_column('comment', 'id')
    # ### end Alembic commands ###
