"""add_title_lower

Revision ID: d5207da2612d
Revises: 6c743c571061
Create Date: 2022-05-22 21:44:25.391712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5207da2612d'
down_revision = '6c743c571061'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('title_lower', sa.String(), nullable=True))
    op.create_index(op.f('ix_news_title_lower'), 'news', ['title_lower'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_title_lower'), table_name='news')
    op.drop_column('news', 'title_lower')
    # ### end Alembic commands ###
